base_local_planner:
  # ilość próbek prędkości
  vx_samples: 50
  vy_samples: 1
  vth_samples: 41
  # granice predkosci robota
  max_vel_x: 0.15
  min_vel_x: 0.03
  max_vel_y: 0
  min_vel_y: 0
  max_vel_th: 1.7
  min_vel_th: -1.7
  # parametry algorytmu planera
  sim_time: 6
  path_distance_bias: 1
  goal_distance_bias: 0.5
  occdist_scale: 0.005
  # granice przyspieszen robota
  acc_lim_th: 8
  acc_lim_trans: 3
  # tolerancja osiągnięcia celu
  yaw_goal_tolerance: 1000
  xy_goal_tolerance: 0.1
  # czy robot jest holonomiczny
  holonomic_robot: false 
