base_local_planner:
  # granice predkosci robota
  vx_samples: 50
  vy_samples: 1
  vth_samples: 41
  max_vel_trans: 1
  # min_vel_trans: 0.000000001
  max_vel_x: 0.15
  min_vel_x: 0.03
  max_vel_y: 0
  min_vel_y: 0
  # oscillation_reset_dist: 0.1
  # max_vel_rot: 1.7
  max_vel_th: 1.7
  min_vel_th: -1.7
  max_vel_theta: 1.7
  min_vel_theta: -1.7

  sim_time: 6
  path_distance_bias: 1
  goal_distance_bias: 0.5
  occdist_scale: 0.005
  # min_vel_rot: 0.1
  max_vel_rot: 1.7
  # max_in_place_vel_th: 1.7
  # min_in_place_vel_th: -1.7
  # max_in_place_vel_rot: 1.7
  # min_in_place_vel_rot: 0.2
  # trans_stopped_vel: 0.1
  # rot_stopped_vel: 0.1


  # granice przyspieszen robota
  acc_lim_th: 8
  acc_lim_trans: 3
  # acc_lim_theta: 30
  # acc_lim_x: 3
  # acc_lim_y: 0

  yaw_goal_tolerance: 1000
  xy_goal_tolerance: 0.1
  holonomic_robot: false # czy robot jest holonomiczny