obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[2, 3], [2, -3], [-2, -3], [-2, 3]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: laser_scan, marking: true, clearing: true}

