# parametry wspólne globalnej i lokalnej mapy kosztów
footprint: [[0.24, 0.18], [0.24, -0.18], [-0.24, -0.18], [-0.24, 0.18]] # punty graniczne bazy jezdnej robota
footprint_padding: 0
#robot_radius: ir_of_robow
# inflation_radius: 0.02 # minimalna odlegosc od przeszkod, aby sciezka nie miala dodatkowego kosztu (zwiaznego z odlegoscia)
always_send_full_costmap: true
